---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-jenkins
  namespace: jenkins-routed
spec:
  capacity:
    storage: 6Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /srv/nfs
    server: 172.31.19.85
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-jenkins
  namespace: jenkins-routed
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi