- name: Para poder acceder a los pods desde fuera de kubernetes necesitamos un ingress controller
  shell: "kubectl --kubeconfig=/home/{{user}}/.kube/config apply -f https://raw.githubusercontent.com/haproxytech/kubernetes-ingress/master/deploy/haproxy-ingress.yaml"

- name: Pedimos el comando que nos va a permitir unirnos al cluster
  shell: "kubeadm --kubeconfig=/home/{{user}}/.kube/config token create --print-join-command"
  register: join_command_raw
 
- name: Seteamos el comando join en un fact
  set_fact:
    join_command: "{{ join_command_raw.stdout_lines[0] }}"
