- name: Creando cluster de kubernetes
  hosts: [master]
  vars_files:
    - "group_vars/general_config.yaml"
    - "group_vars/private_ips.yaml"
  become: true
  gather_facts: true
  roles:
   - init_k8s_master

- name: Unión de nodos
  hosts: [workers]
  become: true
  gather_facts: true
  roles:
   - init_k8s_worker