- name: Configurando los archivos /etc/hosts
  hosts: all
  vars_files:
    - "group_vars/private_ips.yaml"
  become: true
  gather_facts: true
  roles:
   - config_hosts
- name: Preparando el servidor NFS
  hosts: [nfs]
  vars_files:
    - "group_vars/general_config.yaml"
    - "group_vars/private_ips.yaml"
  become: true
  gather_facts: true
  roles:
   - config_nfs_master
- name: Preparando el cliente NFS
  hosts: [workers, master]
  vars_files:
    - "group_vars/general_config.yaml"
    - "group_vars/private_ips.yaml"
  become: true
  gather_facts: true
  roles:
   - config_nfs_client